module.exports = [

  { 
    id: 1,
    pic: "/images/headshot.png",
    name: "Chris",
    dob: "1989",
    hair_color: "ginger",
    shoe_size: 9,
    bloodtype: "A",
    released: false
  },
  { id: 2,
    pic: "/images/headshot.png",
    name: "Lewis",
    dob: "1988",
    hair_color: "black",
    shoe_size: 8,
    bloodtype: "B",
    released: false
  },
  { id: 3,
    pic: "/images/headshot.png",
    name: "Aidan",
    dob: "1985",
    hair_color: "brown",
    shoe_size: 11,
    bloodtype: "AB",
    released: false
  },
  { id: 4,
    pic: "/images/headshot.png",
    name: "Jeff",
    dob: "1990",
    hair_color: "grey",
    shoe_size: 10,
    bloodtype: "O",
    released: false
  }
  // { id: 5,
  //   pic: "/images/headshot.png",
  //   name: "Henry",
  //   dob: "1990",
  //   hair_color: "grey",
  //   shoe_size: 10,
  //   bloodtype: "O",
  //   released: false
  // },
  // { id: 6,
  //   pic: "/images/headshot.png",
  //   name: "Hamish",
  //   dob: "1990",
  //   hair_color: "grey",
  //   shoe_size: 10,
  //   bloodtype: "O",
  //   released: false
  // },
  // { id: 7,
  //   pic: "/images/headshot.png",
  //   name: "David",
  //   dob: "1990",
  //   hair_color: "grey",
  //   shoe_size: 10,
  //   bloodtype: "O",
  //   released: false
  // },
  // { id: 8,
  //   pic: "/images/headshot.png",
  //   name: "Zak",
  //   dob: "1990",
  //   hair_color: "grey",
  //   shoe_size: 10,
  //   bloodtype: "O",
  //   released: false
  // },
  // { id: 9,
  //   pic: "/images/headshot.png",
  //   name: "Harry",
  //   dob: "1990",
  //   hair_color: "brown",
  //   shoe_size: 11,
  //   bloodtype: "A",
  //   released: false
  // },
  // { id: 10,
  //   pic: "/images/headshot.png",
  //   name: "Wojeck",
  //   dob: "1990",
  //   hair_color: "brown",
  //   shoe_size: 10,
  //   bloodtype: "O",
  //   released: false
  // },
]
